import { cn } from '@/components/utilities/cn';
import {
	AlignJustify,
	Angry,
	ArrowBigDown,
	ArrowBigUp,
	ArrowDown,
	ArrowDownToLine,
	ArrowLeft,
	ArrowLeftCircle,
	ArrowRight,
    ArrowUpRight,
	ArrowRightCircle,
	ArrowUp,
	Award,
    BellDot,    
    Building,
	BadgeCheck,
	BadgeDollarSign,
	Ban,
	Bell,
	BookCheck,
	Box,
	Calendar,
	CaptionsOff,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	ChevronsUpDown,
	CircleCheckBig,
	CircleDollarSign,
	CircleEllipsis,
	CircleHelp,
	CircleOff,
	Clock,
	Cog,
	Cone,
	Copy,
	CreditCard,
	Ellipsis,
	ExternalLink,
	Eye,
	EyeOff,
	FileDown,
	FileLineChart,
	Filter,
	Fingerprint,
	FlaskConical,
	Frown,
	Gauge,
	GaugeCircle,
	Globe,
	GripHorizontal,
	History,
	Inbox,
	InboxIcon,
	Info,
	KeyRound,
	Landmark,
	Laugh,
	LayoutGrid,
	Lightbulb,
	LineChart,
	ListMinus,
	ListTree,
	LogOut,
	Mail,
	Maximize2,
	Meh,
	MessageCircleCode,
	MessageSquare,
	MessageSquareMore,
	MessagesSquare,
	Minimize2,
	Minus,
	MonitorCheck,
	Moon,
	MousePointerClick,
	MoveDown,
	MoveUp,
	MoveUpRight,
	Pause,
	Pencil,
	Phone,
	PlayIcon,
	Plus,
	PlusCircle,
	PrinterCheck,
	Receipt,
	Rocket,
	RotateCcw,
	Save,
	ScanSearch,
	Search,
	SendHorizontal,
	Settings,
	ShoppingBag,
	ShoppingCart,
	Smile,
	Star,
	Store,
	Sun,
	Table,
	Tag,
	Trash,
	User,
	UserSquare,
	Users,
	VenetianMask,
	Waypoints,
	Workflow,
	Wrench,
	X,
	Zap,
    CircleDot,
    Crown, 
    Download,
    Edit,
    FileText,
    Flag,
    FolderOpen,
    GripVertical,
    Heart,
    HeartOff,
    HelpCircle,
    Home,
    Image,
    Laptop,
    Loader2,
    Lock,
    Menu, 
} from 'lucide-react';

export const icons = {
    FileDown,
	CaptionsOff,
	ArrowRightCircle,
    Cog,
	Cone,
	ArrowLeftCircle,
	Gauge,
    BookCheck,
	Box,
    Award,
	BadgeCheck,
	BadgeDollarSign,
	Ban,
	FileLineChart,
	Fingerprint,
	FlaskConical,
	Frown,
	GaugeCircle,
	Globe,
	GripHorizontal,
	History,
	Inbox,
	InboxIcon,
	ArrowDownToLine,
    Ellipsis,
	ExternalLink,
    KeyRound,
	Landmark,
	Laugh,
	LayoutGrid,
	Lightbulb,
	LineChart,
	ListMinus,
	ListTree,
    Maximize2,
	Meh,
    ChevronsUpDown,
	CircleCheckBig,
	CircleDollarSign,
	CircleEllipsis,
	CircleHelp,
	CircleOff,
	MessageCircleCode,
    AlignJustify,
    Angry,
    ArrowBigDown,
    ArrowBigUp,
    ArrowDown,
    AlignJustify: AlignJustify,
    ArrowBigDown: ArrowBigDown,
    ArrowBigUp: ArrowBigUp,
    ArrowDown: ArrowDown,
    ArrowLeft: ArrowLeft,
    ArrowRight: ArrowRight,
    ArrowUp: ArrowUp,
    ArrowUpRight: ArrowUpRight,
    Bell: Bell,
    BellDot: BellDot,
    Calendar: Calendar,
    Check: Check,
    ChevronDown: ChevronDown,
    ChevronLeft: ChevronLeft,
    ChevronRight: ChevronRight,
    ChevronUp: ChevronUp,
    CircleDot: CircleDot,
    Clock: Clock,
    Copy: Copy,
    CreditCard: CreditCard,
    Crown: Crown,
    Download: Download,
    Edit: Edit,
    Eye: Eye,
    FileText: FileText,
    Filter: Filter,
    Flag: Flag,
    FolderOpen: FolderOpen,
    Globe: Globe,
    GripVertical: GripVertical,
    Heart: Heart,
    HeartOff: HeartOff,
    HelpCircle: HelpCircle,
    Home: Home,
    Image: Image,
    Info: Info,
    Laptop: Laptop,
    Loader2: Loader2,
    Lock: Lock,
    LogOut: LogOut,
    Mail: Mail,
    Menu: Menu,
    MessageSquare: MessageSquare,
    MessageSquareMore: MessageSquareMore,
    MessagesSquare: MessagesSquare,
    Minimize2: Minimize2,
    Minus: Minus,
    MonitorCheck: MonitorCheck,
    Moon: Moon,
    MousePointerClick: MousePointerClick,
    MoveDown: MoveDown,
    MoveUp: MoveUp,
    MoveUpRight: MoveUpRight,
    Pause: Pause,
    Pencil: Pencil,
    Phone: Phone,
    PlayIcon: PlayIcon,
    Plus: Plus,
    PlusCircle: PlusCircle,
    PrinterCheck: PrinterCheck,
    Receipt: Receipt,
    Rocket: Rocket,
    RotateCcw: RotateCcw,
    Save: Save,
    ScanSearch: ScanSearch,
    Search: Search,
    SendHorizontal: SendHorizontal,
    Settings: Settings,
    ShoppingBag: ShoppingBag,
    ShoppingCart: ShoppingCart,
    Smile: Smile,
    Star: Star,
    Store: Store,
    Sun: Sun,
    Table: Table,
    Tag: Tag,
    Trash: Trash,
    User: User,
    UserSquare: UserSquare,
    Users: Users,
    VenetianMask: VenetianMask,
    Waypoints: Waypoints,
    Workflow: Workflow,
    Wrench: Wrench,
    X: X,
    Zap: Zap,
}


export const Icon = ({ size, currentColor, className, target, ...prop }) => {
	const { color, hoverColor, ...restProps } = prop;
	const IconComponent = icons[prop.name];

	const isCustomSize = typeof size === 'number';

	const iconDefaultSize = size || 'default';

	const iconSize = {
		default: 18,
		xs: 12,
		sm: 16,
		md: 18,
		lg: 24,
		xl: 32,
		'2xl': 48,
		'3xl': 64,
		'4xl': 48,
	};

	const Wrapper = ({ children }) => {
		return children;
	};

	return (
		<Wrapper>
			<IconComponent
				size={isCustomSize ? size : iconSize[iconDefaultSize]}
				className={cn([
					!currentColor && 'text-neutrals-text-primary',
					color && `text-${color}`,
					hoverColor && `${hoverColor}`,
					className,
				])}
				{...restProps}
			/>
		</Wrapper>
	);
};

export const IconWrapper = ({
	backgroundColor,
	className,
	rounded,
	borderColor,
	onClick,
	hoverBGColor,
	hoverColor,
	...iconProps
}) => {
	return (
		<div
			onClick={onClick}
			className={cn([
				'group',
				onClick && 'cursor-pointer',
				rounded ? 'rounded-full' : 'rounded-sm',
				backgroundColor ? `bg-${backgroundColor}` : 'bg-background',
				hoverBGColor && `${hoverBGColor}`,
				borderColor && `border border-${borderColor}`,
				className,
			])}
		>
			<Icon hoverColor={hoverColor} {...iconProps} />
		</div>
	);
};
